README.md
Adding this information to the ReadMe.
=> Updating with Microsoft Open Source Code of Conduct information

Sharing/Src/Projects/SessionManagerUniversal.UI/SessionManagerUniversal.UI.csproj
To resolve part of #21 
Thanks @jwittner for pointing it out
=> Fix Allow Unsafe Code on ARM in SessionManagerUniversal.UI

Sharing/Src/Source/Client/ClientWrapperAPI.h, Sharing/Src/Source/Client/ClientWrapperAPI_CSharp.cpp, Sharing/Src/Source/Client/ClientWrapperAPI_CSharp.h, Sharing/Src/Source/Client/ClientWrapperAPI_Java.cpp, Sharing/Src/Source/Client/ClientWrapperAPI_Java.h
Enabling Network Discovery in SharingClient similar to Profiler as per #25
=> Added the Discovery Client into the SharingClient dll.

Sharing/Src/Projects/SessionManager.UI/SessionManager.UI.csproj, Sharing/Src/Projects/SessionManagerUniversal.UI/SessionManagerUniversal.UI.csproj, Sharing/Src/Source/Client/ClientWrapperAPI.h, Sharing/Src/Source/Client/ClientWrapperAPI_CSharp.cpp, Sharing/Src/Source/Client/ClientWrapperAPI_CSharp.h, Sharing/Src/Source/Client/ClientWrapperAPI_Java.cpp, Sharing/Src/Source/Client/ClientWrapperAPI_Java.h
Resolves issues I had with #26 after I'd merged it.
=> Add back in discovery client plus fixes.

README.md, Sharing/README.md, Sharing/Src/Source/Docs/ExtendedDocs/GettingStarted.md
Getting started was undiscoverable.
Fixes #28
=> Added breadcrumbs to deep sharing docs

Sharing/README.md
=> Fix link to Getting Started

Sharing/Src/Source/Common/Public/CommonSettings.h
=> Set max session name to 1024

Sharing/Src/Source/Client/ClientWrapperAPI_CSharp.cpp, Sharing/Src/Source/Client/ClientWrapperAPI_Java.cpp, Sharing/Src/Source/Common/Private/NewSessionRequest.cpp, Sharing/Src/Source/Common/Private/NewSessionRequest.h, Sharing/Src/Source/Common/Private/SessionManagerImpl.cpp, Sharing/Src/Source/Common/Private/SessionManagerImpl.h, Sharing/Src/Source/Common/Public/SessionManager.h, Sharing/Src/Source/SharingService/SessionServer.cpp
=> Allow creating persistent sessions from client

CONTRIBUTING.md
I also started a similar [pull request for HoloToolkit-Unity](https://github.com/Microsoft/HoloToolkit-Unity/pull/429).
=> Update contribution instructions for Microsoft employees

Sharing/Src/Source/Common/Private/DiscoveryClientImpl.cpp, Sharing/Src/Source/Common/Private/DiscoveryClientImpl.h, Sharing/Src/Source/Common/Private/ProfileManagerImpl.cpp, Sharing/Src/Source/SharingService/SessionServer.cpp
=> Fix DiscoveryClient functionality

SpectatorViewPlugin/README.md
Setting x86 was not mentioned.
I also updated some formatting to properly adhere to markdown guidelines.
=> Update SpectatorView build steps

SpectatorViewPlugin/README.md
Add information on what this project is for and how it can be used. Added additional information for troubleshooting compile issues.
=> Update SpectatorViewPlugin README.md

GpuStats/GpuStatsUniversal/GpuStatsUniversal.vcxproj
Updates to VS2017 and toolset v141.
=> Update GPUStats to toolset v141

SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin/MarkerDetector.cpp, SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin/MarkerDetector.h, SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin.cpp
adding additional comments to clarify behavior
renamed some struct fields to have consistent capitalization
=> Adding additional comments to clarify behavior

README.md
Adding a link to https://github.com/microsoft/MixedRealityToolkit-Unreal in the README.
=> Adding a link to MRTK-Unreal

azure-pipelines.yml
This was causing issues on the internal machines.
=> NuGet not needed

.gitignore, SpatialMapping/PlaneFinding/Tests/TestApp/Program.cs, SpatialMapping/PlaneFinding/Tests/TestHelpers/UnityEngineTypes.cs, SpatialMapping/PlaneFinding/Tests/TestHelpers/Util.cs, SpatialMapping/PlaneFinding/Tests/UnitTests/TestCases.cs, SpatialMapping/PlaneFinding/UnityAddon/Microsoft.MixedReality.Toolkit.PlaneFinding.asmdef, SpatialMapping/PlaneFinding/UnityAddon/Microsoft.MixedReality.Toolkit.PlaneFinding.asmdef.meta, SpatialMapping/PlaneFinding/UnityAddon/PlaneFinding.cs, SpatialMapping/PlaneFinding/UnityAddon/PlaneFinding.cs.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/uap_ARM.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/uap_ARM/PlaneFinding.dll.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/uap_ARM64.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/uap_ARM64/PlaneFinding.dll.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/uap_x64.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/uap_x64/PlaneFinding.dll.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/uap_x86.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/uap_x86/PlaneFinding.dll.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/x64.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/x64/PlaneFinding.dll.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/x86.meta, SpatialMapping/PlaneFinding/UnityAddon/Plugins/x86/PlaneFinding.dll.meta, SpatialMapping/PlaneFinding/UnityAddon/package.json, SpatialMapping/PlaneFinding/UnityAddon/package.json.meta, azure-pipelines.yml
1. Updates script namespaces to match MRTK
1. Adds a package.json for UPM packaging
1. Adds a packaging step to the pipeline for publishing a .tgz to Azure Artifacts
1. Removes a stale `#pragma warning disable` from _old_ versions of Unity 👴
1. Adds meta files for everything in the UPM package
1. Updates the test console app to pause before closing and updates the printed message to be more accurate
=> Add package.json and packaging step to pipeline

GpuStats/GpuStats.sln, GpuStats/GpuStats/GpuStats.vcxproj, GpuStats/GpuStatsUniversal/GpuStatsUniversal.vcxproj
Also updates the output paths to match other solutions
=> Add ARM64 to GpuStats

EditorMotionControllerDLL/EditorMotionController/EditorMotionController.cpp
Old commit / branch (Nov 21, 2018!) that I figure I should merge
=> Cache the SpatialInteractionManager instead of reloading it every time

GpuStats/UnityAddon/package.json
Aligns with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9023
=> Add msftFeatureCategory and increment version

Input/MicStreamSelector/Projects/MicStreamSelector_UWP/MicStreamSelector_UWP.vcxproj, Input/MicStreamSelector/Projects/MicStreamSelector_Win32/MicStreamSelector.vcxproj, azure-pipelines.yml
Fixes the build locally for me. Should fix the build on the pipeline.
=> Update using directories and versions

Input/MicStreamSelector/Projects/MicStreamSelector_Win32/MicStreamSelector.vcxproj
c:\program files... -> $(VCIDEInstallDir)
=> mic stream pipeline: replace literal tool path

CI/azure-pipelines.yml
this change will enable us to build and distribute the new tts plugin for desktop windows projects
=> add winrttts plugin build

CI/Templates/Tasks/pack.yml
Update codesign ADO task to the latest using cert authentication
=> Update codesign ADO task to the latest using cert authentication

WinRTTextToSpeech/WinRTTextToSpeech/WinRTTextToSpeech.vcxproj
Resolve binskim errors found with new pipeline
=> Enable control flow guard and secure checksums to resolve binskim errors

Pipeline/Templates/Tasks/pack.yml, Pipeline/azure-pipelines.yml
Yaml to create a new pipeline that extends the 1ES templates
=> Add 1ES pipeline

Pipeline/azure-pipelines.yml, Pipeline/config/CredScanSuppressions.json
=> Add suppressions

Pipeline/azure-pipelines.yml, Pipeline/config/TSAOptions.json
Add schedule and bug upload to the builds
=> Add schedule and bug upload to the builds

WinRTTextToSpeech/WinRTTextToSpeech/WinRTTextToSpeech.vcxproj
Add spectre mitigation to compile
=> Add spectre mitigation to compile
