SpatialMapping/PlaneFinding/PlaneFinding/FindPlanes.cpp

As the `GetMean()` method was included in public interface it still can be called before `AddVertex(_)` method.
Instead of raising Division By Zero exception it's better to return the Null Object (or limit this method to private access). Up to you :)

return null object to avoid Division By Zero error

---

SpatialMapping/PlaneFinding/PlaneFinding/PlaneFinding.Editor/PlaneFinding.Editor.vcxproj

Addresses #7 
I am also changing the tag from TargetPlatformVersion to WindowsTargetPlatformVersion. I'm not sure of the difference, but in Visual Studio when I used the "Retarget solution" command it added a WindowsTargetPlatformVersion tag, but that didn't work while there was still an older TargetPlatformVersion tag. Other projects don't seem to use the TargetPlatformVersion tag, so hopefully WindowsTargetPlatformVersion is the correct tag to use. Please let me know if this seems incorrect.

upgrade Windows SDK version from 10.0.10502.0 to 10.0.10586.0

---

.gitignore

Addresses #9 
Sorry about the confusion, I have submitted this pull request twice because GitHub was having delays updating this morning and I deleted and recreated the branch while trying to figure out what was going on.

Ignore Debug, Release, bin, and obj folders created by PlaneFinding when building and running tests

---

Sharing/Src/Solutions/VisualStudio/HoloToolkit.Sharing.sln

SessionManagerUniversal.UI dependes on code from CSharpWrapperAPI and the
DLL/PDB from ClientUnivseralCSharp, but was building before they were and
so would fail itself.
Fixes #31

Fix SessionManagerUniversal.UI dependency issues in multiprocess builds

---

SpatialUnderstanding/Src/TestApp/MainPage.xaml.cpp
SpatialUnderstanding/Src/TestApp/TestApp.vcxproj
SpatialUnderstanding/Src/TestApp/TestApp.vcxproj.filters

Previously, it was necessary to manually copy this file into the appropriate place before running a test. Now, the file is included in the solution so that it will automatically be deployed with TestApp.
This fixes #90.

embed dynMeshTest_0.out test file in TestApp project

---

SpatialUnderstanding/Build.bat
SpatialUnderstanding/CopyToUnity.bat

Fixes #99.
These batch files are modeled on the approach used in Sharing (BuildAll.bat, DeploySDKToUnity.bat).

Batch files for building and copying binaries to HoloToolkit-Unity

---

Sharing/Src/Source/SharingService/SessionServer.cpp

The SharingService would previously ignore requests for persistent sessions and would always create an ad-hoc session.  This change honors the SessionType flag passed by the user.

Allow persistent sessions to be created in the SharingService

---

SpatialInput/Libs/Gltf/Gltf.vcxproj
SpatialInput/Libs/Neso/Neso.vcxproj
SpatialInput/Libs/Pbr/Pbr.vcxproj
SpatialInput/Libs/SpatialInputUtilities/SpatialInputUtilities.vcxproj
SpatialInput/Samples/DemoRoom/AppView.cpp
SpatialInput/Samples/DemoRoom/DemoRoom.vcxproj
SpatialInput/Samples/DemoRoom/Package.appxmanifest
SpatialInput/Samples/DemoRoom/PaintStrokeSystem.cpp
SpatialInput/Samples/DemoRoom/PaintingSystem.cpp
SpatialInput/Samples/RenderController/AppView.cpp
SpatialInput/Samples/RenderController/AppView.h
SpatialInput/Samples/RenderController/Common/CameraResources.cpp
SpatialInput/Samples/RenderController/Common/CameraResources.h
SpatialInput/Samples/RenderController/Common/DeviceResources.cpp
SpatialInput/Samples/RenderController/Common/DeviceResources.h
SpatialInput/Samples/RenderController/Common/DirectXHelper.h
SpatialInput/Samples/RenderController/Common/StepTimer.h
SpatialInput/Samples/RenderController/ControllerRenderSample.sln
SpatialInput/Samples/RenderController/ControllerRenderSample.vcxproj
SpatialInput/Samples/RenderController/ControllerRenderSampleMain.cpp
SpatialInput/Samples/RenderController/ControllerRenderSampleMain.h
SpatialInput/Samples/RenderController/ControllerRenderer.cpp
SpatialInput/Samples/RenderController/ControllerRenderer.h
SpatialInput/Samples/RenderController/SpinningCubeRenderer.cpp
SpatialInput/Samples/RenderController/SpinningCubeRenderer.h
SpatialInput/Samples/RenderController/pch.cpp
SpatialInput/Samples/RenderController/pch.h

1. Fixed a few crashing bugs
2. Removed remaining project dependency to c++/cx
3. Added some missing licensing headers.

Fix a few bugs in SpatialInput libraries and sample apps

---

UnityEditorMotionControllerModelDLL/MotionControllerModel/MotionControllerModel.cpp

Related to Microsoft/MixedRealityToolkit-Unity#1645

[MotionControllerModel.dll] Fix to get window by name instead of the active window

---

Input/MicStreamSelector/Projects/MicStreamSelector_Win32/MicStreamSelector.vcxproj

[(Error: Fatal Error C1107) Project Setting Issue for compiling input/MicStreamSelector Solution]
Issue Statement:
Program cannot assembly file "platform.winmd" when compiling the entire solution of  input/MicStreamSelector, if the compiler is non-Enterprise Visual Studio 2017
Solution:
Use a macro for the project setting.

[(Error: Fatal Error C1107) Project Setting Issue for compiling under non-Enterprise VS2017

---

SpectatorViewPlugin/README.md

The suggested commit for vcpkg failed locally for me based on a bad nuget package hash for 7-zip 18.1.0. Using 068032bc548817a04709970f76268a6d7b1767c7 with a reverted 7-zip version unblocked my local build.

Suggested commit for vcpkg didn't work

---

SpatialInput/External/tiny_gltf.h

In the LoadExternalFile function the stream needs to seek back to the beginning before the file is read.

Seek back to beginning before reading file

---

SpectatorViewPlugin/README.md

Update README.md to use correct opencv dll versions. Moving from 3.4.1 to 3.4.3 based on vcpkg changes

Update README.md to use correct opencv dll versions

---

SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin/MarkerDetector.cpp
SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin/MarkerDetector.h
SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin.cpp
SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin.vcxproj

This refactor is related to work in https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/feature/spectatorView 
Changes include the following:
1) The dll is reformatted so that plugin functions use float arrays/pointers. This avoids having to call unsafe code in the C# wrapper class within unity.
2) The dll is reformatted to require camera intrinsic and lens distortion values when detecting markers. These values can be obtained via a new HoloLensCamera wrapper  (https://github.com/chrisfromwork/MixedRealityToolkit-Unity/blob/refactorMarkerDetection/Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Utilities/HoloLensCamera.cs )

Refactoring SpectatorView Plugin

---

GpuStats/GpuStats/GpuStats.cpp
GpuStats/GpuStats/UnityNativeRenderingPlugin.def

Previously, one of the errors cases (query not found) would return 0, which can't be distinguished from the possible case of a query returning 0 by virtue of being too short (unlikely but not impossible).
Now errors are more clear.
Corresponding script changes in MRTK-Unity: https://github.com/botrif/MixedRealityToolkit-Unity/tree/htk_development

Return negative values on errors and fix null pointer crash when deinitializing

---

SpatialMapping/PlaneFinding/Tests/TestApp/Program.cs
SpatialMapping/PlaneFinding/Tests/TestHelpers/Util.cs
SpatialMapping/PlaneFinding/Tests/UnitTests/TestCases.cs

A namespace was changed, but usings weren't.

Fix a few using statements in PlaneFinding test code

---

SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin.Editor/SpectatorViewPlugin.Editor.cpp
SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin.Unity.nuspec
SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin.cpp

Some how "ids" lost its capitalization breaking our dll import.

Fix a bad function name

---

SpectatorViewPlugin/SpectatorViewPlugin/SharedFiles/ArUcoMarkerDetector.cpp

This change makes sure that the _detectedMarkers set is cleared before populating it with the results of a new detection. Prior to this, if a marker was detected previously but not in the current image, its stale data would be reported again.

Ensure the detected markers set from the previous detection is cleared

---

.gitignore
DotNetNativeWorkaround/DotNetNativeWorkaround.sln
DotNetNativeWorkaround/DotNetNativeWorkaround/DotNetNativeWorkaround.cpp
DotNetNativeWorkaround/DotNetNativeWorkaround/DotNetNativeWorkaround.vcxproj
DotNetNativeWorkaround/DotNetNativeWorkaround/DotNetNativeWorkaround.vcxproj.filters
DotNetNativeWorkaround/DotNetNativeWorkaround/dllmain.cpp
DotNetNativeWorkaround/DotNetNativeWorkaround/pch.cpp
DotNetNativeWorkaround/DotNetNativeWorkaround/pch.h
DotNetNativeWorkaround/DotNetNativeWorkaround/targetver.h
DotNetNativeWorkaround/README.md
DotNetNativeWorkaround/build.bat

This solution provides a workaround for a .NET Native (used when building a Master build for a Unity app built with the .NET backend) bug, where `IInspectable` pointers cannot be marshaled from native to managed code using `Marshal.GetObjectForIUnknown`.

.NET Native workaround for IInspectable bug

---

SpatialMapping/PlaneFinding/Tests/TestHelpers/Util.cs
SpatialMapping/PlaneFinding/UnityAddon/PlaneFinding.cs

Update the plane finding scripts a bit to follow the MRTK coding guidelines, as well as porting over some changes that were checked into the HTK-Unity repo but never brought back here.

Port some changes from the HTK-checked-in version of PlaneFinding (and formatting)

---

CI/sign.yml

Looks like this is the only place that doesn't properly handle relative paths

Fix signing output path

---

CI/pack.yml
CI/pipeline.yml
CI/sign.yml
GpuStats/UnityAddon/GpuDurationResult.cs
GpuStats/UnityAddon/GpuDurationResult.cs.meta
GpuStats/UnityAddon/GpuStats.cs
GpuStats/UnityAddon/GpuTimingCamera.cs
GpuStats/UnityAddon/package.json

1. Update Unity scripts to match the latest state of the plug-in (corresponds to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/3344, which we didn't end up taking into HTK)
1. Update GPUStats version to 1.0.0 for release, dropping the `-preview`
1. Also lowers the specified Unity version to 2018.4, since we don't have any specific dependencies on 2019.

Update scripts for GPUStats and update version to 1.0.0 (no preview)

---

GpuStats/UnityAddon/GpuStats.cs
GpuStats/UnityAddon/GpuTimingCamera.cs

Re-adds an event from https://github.com/microsoft/MixedRealityToolkit-Unity/pull/3344 that wasn't ported over in #250.

Gpu timing camera event

---

WinRTTextToSpeech/WinRTTextToSpeech/WinRTTextToSpeech.vcxproj

this change should enable the pipeline to properly build the winrt text to speech dll

switch to vs 2019 compiler

---

CI/Templates/pipeline.yml
CI/azure-pipelines.yml

this change makes it possible to configure the pipeline scripts (yml) to specify the desired target platforms that will be built. it was needed for the winrttexttospeech plugin as it only needs x86 and x64 builds

enable filtering of target platforms during ci

---

WinRTTextToSpeech/UnityAddon/CHANGELOG.md
WinRTTextToSpeech/UnityAddon/WinRTTextToSpeechPinvokes.cs
WinRTTextToSpeech/UnityAddon/package.json
WinRTTextToSpeech/WinRTTextToSpeech/WinRTTextToSpeech.cpp

Paired with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11458
Adds support for a custom voice name to the windows TTS package. This allows MRTK users to use custom voices with TTS on editor and standalone builds

Add support for custom voice name to windows TTS

---

WinRTTextToSpeech/UnityAddon/package.json

Updated the MRTK Windows Text-To-Speech Plugin package to be compatible with Unity's UPM Asset Store.
‼️ Note, the min Unity version supporting UPM Asset Store packages is 2021.3.26f1. That's why you see "unityRelease"="26f1". This change won't prohibit people from obtaining the this package via the MR Feature Tool or scoped registries on older versions of the Unity.
* Had to specify unity patch release. The minimum supported version for the UPM Asset Store is 2021.3.26f1, hence this patch number
* Had to specify a documentation URL
- Fixes: https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/518

Update the MRTK Windows Text-To-Speech Plugin package to be compatible with Unity's UPM Asset Store.

---

WinRTTextToSpeech/UnityAddon/CHANGELOG.md
WinRTTextToSpeech/UnityAddon/package.json

In order to publish UMP Packages to the Unity Store, Unity requires that the package's CHANGELOG.md follows the [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)  format.  Fixing this, and updating version number.

Updating CHANGELOG.md to satisfy UMP package publishing requirements

---

CI/Templates/Tasks/pack.yml
WinRTTextToSpeech/UnityAddon/CHANGELOG.md
WinRTTextToSpeech/UnityAddon/README.md.meta
WinRTTextToSpeech/UnityAddon/package.json

The Unity Asset Store requires that the `Documentation~` not have `.meta` files.  This change avoids copying the README.md.meta file to `the Documentation~` folder.

Updating TTS package to meeting Unity Asset Store requirements
